engines:
  csslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true

ratings:
  paths:
  - "**.css"
  - "**.php"
  - "**.module"
  - "**.inc"

languages:
   PHP: true
   JavaScript: true

exclude_paths:
- "vendor/**/*"
- "tests/**/*"
- "tests/*"